// Mocks generated by Mockito 5.4.2 from annotations
// in picture_of_the_day/test/data/remote_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:picture_of_the_day/core/http/http_service.dart' as _i2;
import 'package:picture_of_the_day/domain/entities/picture_entity.dart' as _i3;

import 'remote_repository_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpService_0 extends _i1.SmartFake implements _i2.HttpService {
  _FakeHttpService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureEntity_1 extends _i1.SmartFake implements _i3.PictureEntity {
  _FakePictureEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockRemoteRepository extends _i1.Mock
    implements _i4.MockRemoteRepository {
  @override
  _i2.HttpService get httpService => (super.noSuchMethod(
        Invocation.getter(#httpService),
        returnValue: _FakeHttpService_0(
          this,
          Invocation.getter(#httpService),
        ),
        returnValueForMissingStub: _FakeHttpService_0(
          this,
          Invocation.getter(#httpService),
        ),
      ) as _i2.HttpService);
  @override
  _i5.Future<_i3.PictureEntity> fetchImage() => (super.noSuchMethod(
        Invocation.method(
          #fetchImage,
          [],
        ),
        returnValue: _i5.Future<_i3.PictureEntity>.value(_FakePictureEntity_1(
          this,
          Invocation.method(
            #fetchImage,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.PictureEntity>.value(_FakePictureEntity_1(
          this,
          Invocation.method(
            #fetchImage,
            [],
          ),
        )),
      ) as _i5.Future<_i3.PictureEntity>);
}
