// Mocks generated by Mockito 5.4.2 from annotations
// in picture_of_the_day/test/data/service/picture_retriever_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:picture_of_the_day/domain/entities/picture_entity.dart' as _i4;
import 'package:picture_of_the_day/domain/repository/local_repository.dart'
    as _i2;
import 'package:picture_of_the_day/domain/repository/remote_repository.dart'
    as _i3;

import 'picture_retriever_service_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalRepository_0 extends _i1.SmartFake
    implements _i2.LocalRepository {
  _FakeLocalRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteRepository_1 extends _i1.SmartFake
    implements _i3.RemoteRepository {
  _FakeRemoteRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePictureEntity_2 extends _i1.SmartFake implements _i4.PictureEntity {
  _FakePictureEntity_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockPictureService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockPictureService extends _i1.Mock
    implements _i5.MockPictureService {
  @override
  _i2.LocalRepository get localRepository => (super.noSuchMethod(
        Invocation.getter(#localRepository),
        returnValue: _FakeLocalRepository_0(
          this,
          Invocation.getter(#localRepository),
        ),
        returnValueForMissingStub: _FakeLocalRepository_0(
          this,
          Invocation.getter(#localRepository),
        ),
      ) as _i2.LocalRepository);
  @override
  _i3.RemoteRepository get remoteRepository => (super.noSuchMethod(
        Invocation.getter(#remoteRepository),
        returnValue: _FakeRemoteRepository_1(
          this,
          Invocation.getter(#remoteRepository),
        ),
        returnValueForMissingStub: _FakeRemoteRepository_1(
          this,
          Invocation.getter(#remoteRepository),
        ),
      ) as _i3.RemoteRepository);
  @override
  _i6.Future<_i4.PictureEntity> fetchImage() => (super.noSuchMethod(
        Invocation.method(
          #fetchImage,
          [],
        ),
        returnValue: _i6.Future<_i4.PictureEntity>.value(_FakePictureEntity_2(
          this,
          Invocation.method(
            #fetchImage,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.PictureEntity>.value(_FakePictureEntity_2(
          this,
          Invocation.method(
            #fetchImage,
            [],
          ),
        )),
      ) as _i6.Future<_i4.PictureEntity>);
}
